### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by Satura** [Satura/aqa-2.1#1]
### Описание
После отправки проекта на github, при запуске на AppVeyor процесс заканчивается сообщением "Build failed".
В логе есть слова "java.lang.IllegalStateException: The driver is not executable".  

### Шаги воспроизведения
1. Отправить проект на github
2. Перейти на appveyor по [ссылке](https://ci.appveyor.com/project/Satura/aqa-2-1/branch/master).
3. Наблюдать результат.

### Ожидаемый результат
1. Успешное окончание процесса, сообщение "BUILD SUCCESSFUL" в конце лога. 

### Фактический результат
1. Сообщение об ошибке в тексте лога: 
  `"UITest > initializationError FAILED`
  `java.lang.IllegalStateException: The driver is not executable"`

#### Полный лог
<details>

```

Build started
git clone -q --branch=master https://github.com/Satura/aqa-2.1.git /home/appveyor/projects/aqa-2-1
git checkout -qf edeae7ad360e82cfbfd97508afefefc2a5da4e22
Configuring 'stack'
Enabling JDK 11
Running "install" scripts
java -jar ./artifacts/app-order.jar &
Running "build_script" scripts
./gradlew test --info
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Downloading https://services.gradle.org/distributions/gradle-6.7-bin.zip
2021-01-03 17:07:51.040 [main] TRACE Application - {
    # application.conf @ jar:file:/home/appveyor/projects/aqa-2-1/artifacts/app-order.jar!/application.conf: 6
    "application" : {
        # application.conf @ jar:file:/home/appveyor/projects/aqa-2-1/artifacts/app-order.jar!/application.conf: 7
        "modules" : [
            # application.conf @ jar:file:/home/appveyor/projects/aqa-2-1/artifacts/app-order.jar!/application.conf: 7
            "ru.netology.aqa.ApplicationKt.module"
        ]
    },
    # application.conf @ jar:file:/home/appveyor/projects/aqa-2-1/artifacts/app-order.jar!/application.conf: 2
    "deployment" : {
        # application.conf @ jar:file:/home/appveyor/projects/aqa-2-1/artifacts/app-order.jar!/application.conf: 3
        "port" : 9999
    },
    # Content hidden
    "security" : "***"
}
2021-01-03 17:07:51.280 [DefaultDispatcher-worker-1] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
2021-01-03 17:07:51.736 [DefaultDispatcher-worker-1] INFO  Application - Responding at http://0.0.0.0:9999
.........10%..........20%..........30%..........40%..........50%.........60%..........70%..........80%..........90%..........100%
Initialized native services in: /home/appveyor/.gradle/native
Welcome to Gradle 6.7!
Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support
For more details see https://docs.gradle.org/6.7/release-notes.html
Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Successfully started process 'Gradle build daemon'
The client will now receive all logging from the daemon (pid: 6723). The daemon log file: /home/appveyor/.gradle/daemon/6.7/daemon-6723.out.log
Starting build in new daemon [memory: 536.9 MB]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 2 worker leases.
Watching the file system is disabled
Starting Build
Compiling settings file '/home/appveyor/projects/aqa-2-1/settings.gradle' using SubsetScriptTransformer.
Compiling settings file '/home/appveyor/projects/aqa-2-1/settings.gradle' using BuildScriptTransformer.
Settings evaluated using settings file '/home/appveyor/projects/aqa-2-1/settings.gradle'.
Projects loaded. Root project using build file '/home/appveyor/projects/aqa-2-1/build.gradle'.
Included projects: [root project 'aqa-2.1']
<-------------> 0% CONFIGURING [3s]
> Configure project :
Evaluating root project 'aqa-2.1' using build file '/home/appveyor/projects/aqa-2-1/build.gradle'.
Compiling build file '/home/appveyor/projects/aqa-2-1/build.gradle' using SubsetScriptTransformer.
Compiling build file '/home/appveyor/projects/aqa-2-1/build.gradle' using BuildScriptTransformer.
All projects evaluated.
Selected primary task 'test' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test']
Tasks that were excluded: []
:compileJava (Thread[Daemon worker,5,main]) started.
> Task :compileJava NO-SOURCE
file or directory '/home/appveyor/projects/aqa-2-1/src/main/java', not found
Skipping task ':compileJava' as it has no source files and no previous output files.
:compileJava (Thread[Daemon worker,5,main]) completed. Took 0.064 secs.
:processResources (Thread[Execution worker for ':',5,main]) started.
> Task :processResources NO-SOURCE
file or directory '/home/appveyor/projects/aqa-2-1/src/main/resources', not found
Skipping task ':processResources' as it has no source files and no previous output files.
:processResources (Thread[Execution worker for ':',5,main]) completed. Took 0.005 secs.
:classes (Thread[Execution worker for ':',5,main]) started.
> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:compileTestJava (Thread[Execution worker for ':',5,main]) started.
> :compileTestJava > Resolve dependencies of :testCompileClasspath
> Task :compileTestJava
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/3.141.59/selenium-java-3.141.59.pom to /tmp/gradle_download2793915073008209595bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.pom to /tmp/gradle_download9089208872861828218bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/5.5.1/junit-jupiter-api-5.5.1.pom to /tmp/gradle_download1692024453614473685bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-params/5.5.1/junit-jupiter-params-5.5.1.pom to /tmp/gradle_download18114972604301315469bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/3.141.59/selenium-chrome-driver-3.141.59.pom to /tmp/gradle_download8089922306958854257bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-api/3.141.59/selenium-api-3.141.59.pom to /tmp/gradle_download4952978995364109168bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-firefox-driver/3.141.59/selenium-firefox-driver-3.141.59.pom to /tmp/gradle_download16862191969316488076bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-ie-driver/3.141.59/selenium-ie-driver-3.141.59.pom to /tmp/gradle_download17463863646288994069bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-remote-driver/3.141.59/selenium-remote-driver-3.141.59.pom to /tmp/gradle_download2490410848793737284bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-opera-driver/3.141.59/selenium-opera-driver-3.141.59.pom to /tmp/gradle_download2969966660740905319bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-safari-driver/3.141.59/selenium-safari-driver-3.141.59.pom to /tmp/gradle_download3280213061025553429bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-support/3.141.59/selenium-support-3.141.59.pom to /tmp/gradle_download14521104600794805224bin
Downloading https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom to /tmp/gradle_download1463981818211592556bin
Downloading https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.pom to /tmp/gradle_download3047747231275926264bin
Downloading https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom to /tmp/gradle_download1576177777296026303bin
Downloading https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy-parent/1.8.15/byte-buddy-parent-1.8.15.pom to /tmp/gradle_download9542652061962829729bin
Downloading https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom to /tmp/gradle_download17069929296419333024bin
Downloading https://repo.maven.apache.org/maven2/com/google/guava/guava/25.0-jre/guava-25.0-jre.pom to /tmp/gradle_download10264446662101539851bin
Downloading https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.11.0/okhttp-3.11.0.pom to /tmp/gradle_download3679980150782652065bin
Downloading https://repo.maven.apache.org/maven2/com/google/guava/guava-parent/25.0-jre/guava-parent-25.0-jre.pom to /tmp/gradle_download5339254378101464737bin
Downloading https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom to /tmp/gradle_download228831097509728942bin
Downloading https://repo.maven.apache.org/maven2/com/squareup/okhttp3/parent/3.11.0/parent-3.11.0.pom to /tmp/gradle_download13999674529827035265bin
Downloading https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom to /tmp/gradle_download15477026573852616855bin
Downloading https://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.14.0/okio-1.14.0.pom to /tmp/gradle_download12063592885931899281bin
Downloading https://repo.maven.apache.org/maven2/com/squareup/okio/okio-parent/1.14.0/okio-parent-1.14.0.pom to /tmp/gradle_download14404115610103483387bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-edge-driver/3.141.59/selenium-edge-driver-3.141.59.pom to /tmp/gradle_download7851118959487763834bin
Downloading https://repo.maven.apache.org/maven2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.pom to /tmp/gradle_download7277092112068968999bin
Downloading https://repo.maven.apache.org/maven2/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.pom to /tmp/gradle_download12883545669919000132bin
Downloading https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-commons/1.5.1/junit-platform-commons-1.5.1.pom to /tmp/gradle_download14828163512499906619bin
Downloading https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom to /tmp/gradle_download5870425873209624001bin
Downloading https://repo.maven.apache.org/maven2/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.pom to /tmp/gradle_download2069703950861061383bin
Downloading https://repo.maven.apache.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.pom to /tmp/gradle_download2843444570259769673bin
Downloading https://repo.maven.apache.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.pom to /tmp/gradle_download10409788985827620943bin
Downloading https://repo.maven.apache.org/maven2/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14.pom to /tmp/gradle_download9034623962838918602bin
Downloading https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.pom to /tmp/gradle_download4152839652122527183bin
Downloading https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom to /tmp/gradle_download17756853503352911815bin
Downloading https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_parent/2.1.3/error_prone_parent-2.1.3.pom to /tmp/gradle_download14246360796267632145bin
Downloading https://repo.maven.apache.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom to /tmp/gradle_download7515652764324223322bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/3.141.59/selenium-java-3.141.59.jar to /tmp/gradle_download16855341183601267749bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.jar to /tmp/gradle_download10170681012853857329bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/5.5.1/junit-jupiter-api-5.5.1.jar to /tmp/gradle_download13922758681650072940bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/3.141.59/selenium-chrome-driver-3.141.59.jar to /tmp/gradle_download16167114604614889747bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-edge-driver/3.141.59/selenium-edge-driver-3.141.59.jar to /tmp/gradle_download9495932673814529522bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-ie-driver/3.141.59/selenium-ie-driver-3.141.59.jar to /tmp/gradle_download14085626701237157170bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-firefox-driver/3.141.59/selenium-firefox-driver-3.141.59.jar to /tmp/gradle_download14548193290265084322bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-opera-driver/3.141.59/selenium-opera-driver-3.141.59.jar to /tmp/gradle_download3967571206975416291bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-safari-driver/3.141.59/selenium-safari-driver-3.141.59.jar to /tmp/gradle_download14205752686874772888bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-support/3.141.59/selenium-support-3.141.59.jar to /tmp/gradle_download9910120943163257860bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-remote-driver/3.141.59/selenium-remote-driver-3.141.59.jar to /tmp/gradle_download5781698939843714954bin
Downloading https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-api/3.141.59/selenium-api-3.141.59.jar to /tmp/gradle_download1004840684634596481bin
Downloading https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.jar to /tmp/gradle_download11249067610855022600bin
Downloading https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar to /tmp/gradle_download13119213936863925608bin
Downloading https://repo.maven.apache.org/maven2/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar to /tmp/gradle_download15862246506943569921bin
Downloading https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.11.0/okhttp-3.11.0.jar to /tmp/gradle_download5879444254392325026bin
Downloading https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-commons/1.5.1/junit-platform-commons-1.5.1.jar to /tmp/gradle_download9412692893789571361bin
Downloading https://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar to /tmp/gradle_download5004297951790121776bin
Downloading https://repo.maven.apache.org/maven2/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar to /tmp/gradle_download6586745459372933523bin
Downloading https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar to /tmp/gradle_download7492142883330480798bin
Downloading https://repo.maven.apache.org/maven2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar to /tmp/gradle_download8324243714843871579bin
Downloading https://repo.maven.apache.org/maven2/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar to /tmp/gradle_download3617950197653259701bin
Downloading https://repo.maven.apache.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar to /tmp/gradle_download13560137289149475020bin
Downloading https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar to /tmp/gradle_download4361585749631912317bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-params/5.5.1/junit-jupiter-params-5.5.1.jar to /tmp/gradle_download16981401461100343449bin
Downloading https://repo.maven.apache.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar to /tmp/gradle_download9909630595856586132bin
Caching disabled for task ':compileTestJava' because:
  Build cache is disabled
Task ':compileTestJava' is not up-to-date because:
  No history is available.
The input changes require a full rebuild for incremental task ':compileTestJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Created classpath snapshot for incremental compilation in 2.619 secs. 1 duplicate classes found in classpath (see all with --debug).
:compileTestJava (Thread[Execution worker for ':',5,main]) completed. Took 8.622 secs.
:processTestResources (Thread[Daemon worker,5,main]) started.
> Task :processTestResources NO-SOURCE
file or directory '/home/appveyor/projects/aqa-2-1/src/test/resources', not found
Skipping task ':processTestResources' as it has no source files and no previous output files.
:processTestResources (Thread[Daemon worker,5,main]) completed. Took 0.001 secs.
:testClasses (Thread[Daemon worker,5,main]) started.
> Task :testClasses
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
:test (Thread[Daemon worker,5,main]) started.
Gradle Test Executor 1 started executing tests.
> :test > 0 tests completed
> Task :test
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.5.1/junit-jupiter-engine-5.5.1.pom to /tmp/gradle_download9532360328525715757bin
Downloading https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-engine/1.5.1/junit-platform-engine-1.5.1.pom to /tmp/gradle_download6475879548037568888bin
Downloading https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.5.1/junit-jupiter-engine-5.5.1.jar to /tmp/gradle_download8157705828607266995bin
Downloading https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-engine/1.5.1/junit-platform-engine-1.5.1.jar to /tmp/gradle_download18190449478919211878bin
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  No history is available.
Starting process 'Gradle Test Executor 1'. Working directory: /home/appveyor/projects/aqa-2-1 Command: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Dorg.gradle.native=false @/tmp/gradle-worker-classpath14744823812671077693txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
> :test > Executing test ru.netology.UITest
Gradle Test Executor 1 finished executing tests.
> :test
> Task :test FAILED
UITest > initializationError FAILED
    java.lang.IllegalStateException: The driver is not executable: /home/appveyor/projects/aqa-2-1/driver/geckodriver
        at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
        at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:150)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:141)
        at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:44)
        at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:167)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:190)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at ru.netology.UITest.setUp(UITest.java:36)
1 test completed, 1 failed
Finished generating test XML results (0.017 secs) into: /home/appveyor/projects/aqa-2-1/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.029 secs) into: /home/appveyor/projects/aqa-2-1/build/reports/tests/test
:test (Thread[Daemon worker,5,main]) completed. Took 2.632 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/appveyor/projects/aqa-2-1/build/reports/tests/test/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 23s
2 actionable tasks: 2 executed
Command exited with code 1
Build failed

```

</details>

#### Примечание
Проект успешно собирается и тесты проходят в системах Windows 10 ( сборка 19042.685) x64, Linux Mint 20 "Ulyana" - Cinnamon (64-bit).
Про "The driver is not executable" интернет усердно предлагает сделать с файлом "chmod 777 <путь/имя драйвера>", что тоже было сделано, проект на github'е удален, из проекта драйверы вырезаны, комит, возвращены, коммит и потом уже пуш. И всё это не помогло.

**Comment by Satura** [comment]
А надо было: `git update-index --chmod +x driver/geckodriver`
